### ISSUE TITLE
Whether qrhi will support indirect rendering in the future?

### ISSUE THREAD

**Issue by Italink** [alpqr/qrhibasis#1]
Dear Laszlo Agocs
I am a former Qt user and now a game engine engineer, I have been following QRhi updates since Qt 6.0, I have tried a lot with it, it is really too powerful and elegant
but I've also run into a few issues: it doesn't support Indirect Draw or Indirect Dispatch
These features are critical when implementing GPU-driven rendering pipelines, such as GPU particles, Unreal Engine Nanite technology
I extended it by using the Vulkan API, but it wasn't perfect, therefore, I would like to ask whether QRhi will support indirect rendering in the future?
I recently found your DX12 submission on git, oh my God. why are you so good? you're my hero!
( my English is terrible. Forgive me =.= )

**Comment by alpqr** [comment]
Hello there, it is a valid question. Right now there are no known plans for indirect rendering support, because the primary users of the API (Qt Quick and Qt Quick 3D) do not currently have use cases where this would be essential. There is of course a good chance we will need to revisit this topic at some point in the future, but cannot give any estimates now.
